import Head from "next/head";
import { useEffect, useState } from 'react';
import axios from 'axios';

interface ApiResponse {
  message: string;
}

export default function Home() {
  const [data, setData] = useState<ApiResponse | null>(null);

  // コンポーネントがマウントされたときにバックエンドAPIを呼び出す
  useEffect(() => {
    const apiUrl = process.env.NEXT_PUBLIC_API_URL;

    const fetchData = async () => {
      try {
        // axiosを使ってバックエンドAPIからデータを取得
        const response = await axios.get(`${apiUrl}/api/greeting`);

        // データをステートに保存
        setData(response.data);
      } catch (error) {
        if (axios.isAxiosError(error)) {
          // Axiosエラーの場合、エラーメッセージを取得
          console.error('Axios Error: ', error.response?.data || error.message);
        } else {
          // その他のエラー
          console.error('Error: ', error);
        }
      }
    };

    fetchData();
  }, []);  // 空の依存配列で、コンポーネントが初回マウントされたときのみ実行


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <h1>API response Here!</h1>
          <p>{data ? data.message : 'Loading...'}</p>
        </main>
    </>
  );
}